### ISSUE TITLE
Small freezes while typing in Kotlin file

### ISSUE THREAD

**Issue by zinoviy23** [JetBrains-Research/IRen#2]
**Bug description**
IDE has small frizes while typing in a big Kotlin file. In provided snapshot, we can see, that IRen blocks EDT for executing the editor's write action. Looks like IRen inspection accrues read-lock and doesn't return it to on write actions.

**To Reproduce**
For me it appears on typing in `community/uast/uast-common/src/org/jetbrains/uast/analysis/DependencyGraphBuilder.kt` in IntelliJ repository. Just pressing `Enter` or `Backspace` is enough to cause a freeze.

For stable reproduction, click on [Memory Indicator](https://www.jetbrains.com/help/idea/increasing-memory-heap.html#enable-memory-indicator) to call GC (for droping IRen model caches).

**Snapshot**
Snapshot is available on [google drive](https://drive.google.com/file/d/1gUEkO6GQm2hPd4d7xKgxwMDVqq679zG6/view?usp=sharing).

On this screenshot we can see, that IRen loads model, while EDT is doing nothing
<img width="1468" alt="Screenshot 2022-06-24 at 17 04 04" src="https://user-images.githubusercontent.com/11316903/175563470-7df243a9-db94-45af-9a5d-8a13120ff6ad.png">

And EDT is trying to start to write action, but can't.
<img width="1458" alt="Screenshot 2022-06-24 at 17 05 38" src="https://user-images.githubusercontent.com/11316903/175563721-efb323f4-e519-4485-a0a9-1d96b39faf77.png">

**Possible solution**
As I understand, it is caused by ignoring existing process indicators, with which any inspection is called.
`LimitedTimeRunner` should somehow propagate cancelation of the existing indicator in the current thread to a newly created `org.jetbrains.iren.utils.LimitedRunningTimeIndicator` at `org/jetbrains/iren/utils/LimitedTimeRunner.java:14`.
I think, `com.intellij.concurrency.SensitiveProgressWrapper` should help.

**Desktop (please complete the following information):**
 - Language: Kotlin
 - IDE: IntelliJ IDEA
 - Version: 2022.3

**Additional context**
```
IntelliJ IDEA 2022.3 EAP (Ultimate Edition)
Build #IU-223.725, built on June 24, 2022
Licensed to IntelliJ IDEA EAP user: Aleksandr Izmailov
Expiration date: July 24, 2022
Runtime version: 17.0.3+7-b489.2 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.4
GC: G1 Young Generation, G1 Old Generation
Memory: 16384M
Cores: 10
Metal Rendering is ON
Registry:
    debugger.click.disable.breakpoints=true
    compiler.build.report.statistics=true
    ide.smart.update=true
    freeze.reporter.dump.duration.s=1
    compiler.process.use.portable.caches=true
    ide.experimental.ui=true
    freeze.reporter.dump.interval.ms=50

Non-Bundled Plugins:
    indent-rainbow.indent-rainbow (2.0.2)
    jetbrains.team.auth (223.5)
    com.jetbrains.intellij.code.search.polaris (0.1.785)
    org.jetbrains.idea.grammar (2021.1.2)
    com.intellij.sisyphus (223.621)
    String Manipulation (9.5.0)
    com.jetbrains.idea.safepush (223.5)
    Jetbrains TeamCity Plugin (2022.4.108502)
    com.jetbrains.intellij.api.watcher (6.61.0)
    com.github.davidenkoim.idnamessuggestingplugin (0.1.9)
    izhangzhihao.rainbow.brackets (6.25)

Kotlin: 223-1.7.0-release-282-IJ725
```

**Comment by davidenkoim** [comment]
Hi, sorry for not responding for so long. This bug will be fixed in the next release.
